on: [push]
jobs:
  magic_pod_job:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Prepare testplan
        env:
          TESTRAIL_URL: <YOUR URL>
          TESTRAIL_USER: <YOUR USER ACCOUNT>
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
        run: python testrail_prepare.py
      - name: Install magicpod-api-client
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGICPOD_API_TOKEN }}
        run: bash download_magicpod_api_client.sh
      - name: Run MagicPod
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGICPOD_API_TOKEN }}
          MAGICPOD_ORGANIZATION_NAME: <YOUR ORGANIZATION_NAME>
          MAGICPOD_PROJECT_NAME: <YOUR PROJECT_NAME>
          MAGICPOD_TEST_SETTING_ID: <YOUR SETTING_ID>
        run: python run_magicpod.py
      - name: Add test results to TestRail
        env:
          TESTRAIL_URL: <YOUR URL>
          TESTRAIL_USER: <YOUR USER NAME>
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
        run: python testrail_add_test_result.py
